### ISSUE TITLE
Disable Rules and not entire Category of error.

### ISSUE THREAD

**Issue by jeanrjc** [wysiib/linter-languagetool#18]
If one wants to disable spelling mistakes, you can disable the `TYPOS` rule category but it will block any other rules in that category, e.g. N-Gram verification.

To fix that, and block only rule and not entire category, you can put, in your config file, which contains the path to you ngram dir, the path to another (!) config file with the list of rule you want to disable.

The first config file (you give its path to linter-languagetool in the settings) looks like this:

```
# Path to N-gram directory
languageModel=/Users/foo/bar/bin/ngrams
# Path to your disabled rules
rulesFile=/Users/foo/bar/bin/languagetool_rules.cfg
```

And the rulesFile looks like this, to solve the above mentioned problem:

```
# Disable rules for linter languagetool in Atom
disabledRules.en-US=MORFOLOGIK_RULE_EN_US
```
If the doc could be updated it would be nice for others, and this issue could be closed.

**Comment by wysiib** [comment]
I think we could easily provide a preference for disabled rules in addition to the one for disabled categories. That way, no external configuration file would be needed.

**Comment by jeanrjc** [comment]
It would be nice !

**Comment by wysiib** [comment]
added in version 0.6.1
