### ISSUE TITLE
LanguageTool Still Running

### ISSUE THREAD

**Issue by davidlday** [wysiib/linter-languagetool#19]
On MacOS, the LanguageTool server continues to run after I shut down Atom. A quick look at the code says this is by design. Would it be possible to automatically shut down the server on close, or perhaps make it an option, or is there a specific reason not to do so?

**Comment by wysiib** [comment]
It's not really by design - we just haven't figured out how to safely and reliably shut down the server.

**Comment by davidlday** [comment]
Cool. I'll fork and see if I can help.

**Comment by davidlday** [comment]
BTW - love this package!

**Comment by davidlday** [comment]
Before I go chasing shadows, have you looked into [{BufferedProcess}](https://atom.io/docs/api/v1.21.1/BufferedProcess)?

**Comment by wysiib** [comment]
No, I have not. So far, we are using the process helpers from https://github.com/steelbrain/atom-linter.
