### ISSUE TITLE
Langauge Tool Port Conflict

### ISSUE THREAD

**Issue by davidlday** [wysiib/linter-languagetool#21]
I have two machines where port 8081 is already in use. I cannot change those existing services (work laptops). I'd like to add a configuration item for port, defaulting to 8081.

**Comment by wysiib** [comment]
Can you extract the configuration option from the previous pull request? If so, I would be willing to merge it. Otherwise, I can implement the option myself.

**Comment by davidlday** [comment]
Yep, I'll take care of it - feel free to assign it to me.

**Comment by davidlday** [comment]
@hesstobi 's pr fixes this as well.
