### ISSUE TITLE
JVM Memory Options / JAVA_OPTS

### ISSUE THREAD

**Issue by davidlday** [wysiib/linter-languagetool#30]
I'd like to either add two configuration items to control JVM memory consumption - -Xms and -Xms - set to reasonable defaults (like 256m and 512m) or possibly add a single configuration item with free-form jvm options like the JAVA_OPTS environment variable to give more control over how the language tool service runs.

Thoughts?

**Comment by wysiib** [comment]
Given that these options will probably only be used by experienced users, I think the free-form one would be sufficient. On the other hand, making the memory options easily available could help inexperienced users as well. However, as soon as we introduce those two options seperately, somebody will be asking for a third and fourth option for sure. All in all, I'm leaning towards the free-form option for JVM options. Introducing it is not much work. Do you want to send a pull request? If not, I can implement it in the next few days.

**Comment by davidlday** [comment]
@wysiib - I'll see if I can put something together today. Thanks!

**Comment by wysiib** [comment]
You need any help?

**Comment by davidlday** [comment]
Yes, please. My apologies for letting this get away from me. I've had trouble making the time to tackle this. If you have time to implement, by all means don't wait on me.

And if you could somehow add a few extra hours to every day, that would be cool, too. 😆
