### ISSUE TITLE
Do NOT use public API when local server cannot be startet

### ISSUE THREAD

**Issue by justaskingquestions** [wysiib/linter-languagetool#33]
### Configuration
linter-lnaguagetool set to user local server under /usr/share/java/languagetool/languagetool-server.jar
platform: Arch Linux

### Observed behavior
Upon starting atom, I receive an error message that linter-languagetool was unable to start the local server and **will thus default to use the public API**. The linter continues to work with the external API.

### Expected behavior
I am using Atom to write reports for my clients and sending the contents of a report that is considered confidential to an external API is absolutely out of the question. This is the precise reason I configured linter-languagetool to use a **local server**. If using this local server does not work for some reason, linter-languagetool should **not use an public API unless explicitly instructed to do so.** 

One could argue, that the user is warned about this behavior, but the warning is only displayed for a few seconds so the fact that LT will use the public API might be missed by a user.

**Comment by wysiib** [comment]
I absolutely agree with you. I will add a preference to enable / disable the fallback. The default should indeed be to disable it.

**Comment by wysiib** [comment]
will be integrated in the next release!
