### ISSUE TITLE
How to enable n-gram?

### ISSUE THREAD

**Issue by ReneTC** [wysiib/linter-languagetool#36]
Would love some tips on how to use to find errors using n-gram data. I downloaded the data, and extraded it.

![image](https://user-images.githubusercontent.com/40211569/97087539-372c7f80-162b-11eb-91da-9101b4b48ea0.png)

In the folder, there is an en/ folder. Is that correct? I don't see any additional suggestions compared to the online https://languagetool.org/ .. I would really love your input on this

**Comment by wysiib** [comment]
You cannot provide the ngrams directly using the preference shown in the screenshot. Instead, you need to provide a path to a languagetool configuration file, in which you can configure the ngram data and how it should be used. See https://dev.languagetool.org/finding-errors-using-n-gram-data, Point 4, 'Server Mode'. The Atom preference links to the configuration file mentioned there.

**Comment by ReneTC** [comment]
@wysiib thank you for the comment. Do you know what server they are talking about? I'm using ubuntu and don't know where and with what i should call `--languageModel`

**Comment by wysiib** [comment]
They are talking about the LanguageTool Server. The editor starts it up in the background and them communicates with it via HTTP. You do not need to call anything with that parameter, as the startup is handled by the Atom plugin. However, we pass a configuration file to the LanguageTool Server upon startup. You can use the preferences to provide a path to said configuration file. Thus, you would need to put the equivalent of `--languageModel` into the file. However, I currently do not know how exactly that is supposed to look and I did not find it in the LanguageTool documentation immediately ......
