### ISSUE TITLE
Option to disable icon in status bar

### ISSUE THREAD

**Issue by mfbehrens** [wysiib/linter-languagetool#37]
No offend, but I don't really like the LT info thing in the status bar.

Is it possible to add an option to disable this icon?

Best,
Michael

**Comment by wysiib** [comment]
Hi,
yes, absolutely. I see you already have a solution on your fork. Would you mind creating a pull request? I will release a new version as soon as we have it merged.

**Comment by wysiib** [comment]
Merged, release will follow soon.
